// ----------------------------------------------------------------------

function path(root, sublink) {
  return `${root}${sublink}`;
}

const ROOTS_DASHBOARD = '/dashboard';

// ----------------------------------------------------------------------

export const PATH_AUTH = {
  login: '/login',
  register: '/register',
};

export const PATH_DASHBOARD = {
  root: '/dashboard',
  user: {
    root: path(ROOTS_DASHBOARD, '/user'),
    profile: path(ROOTS_DASHBOARD, '/user/profile'),
    cards: path(ROOTS_DASHBOARD, '/user/cards'),
    list: path(ROOTS_DASHBOARD, '/user/list'),
    new: path(ROOTS_DASHBOARD, '/user/new'),
    edit: (name) => path(ROOTS_DASHBOARD, `/user/${name}/edit`),
    demoEdit: path(ROOTS_DASHBOARD, `/user/reece-chung/edit`),
  },
  userManagement: path(ROOTS_DASHBOARD, '/user-management'),
  roomManagement: path(ROOTS_DASHBOARD, '/room-management'),
  subjectManagement: path(ROOTS_DASHBOARD, '/subject-management'),
  courseManagement: path(ROOTS_DASHBOARD, '/course-management'),
  profile: path(ROOTS_DASHBOARD, '/profile'),
  calendar: path(ROOTS_DASHBOARD, '/calendar'),
  banking: path(ROOTS_DASHBOARD, '/banking'),
  booking: path(ROOTS_DASHBOARD, '/booking'),
  checkout: path(ROOTS_DASHBOARD, '/checkout'),
  invoice: path(ROOTS_DASHBOARD, '/invoice'),
  product: path(ROOTS_DASHBOARD, '/product'),
  analytics: path(ROOTS_DASHBOARD, '/analytics'),
  ecommerce: path(ROOTS_DASHBOARD, '/ecommerce'),
  academy: path(ROOTS_DASHBOARD, '/academy'),
  authDemo: path(ROOTS_DASHBOARD, '/auth-demo'),
  docs: path(ROOTS_DASHBOARD, '/docs'),
  permissionDenied: path(ROOTS_DASHBOARD, '/permission-denied'),
  blank: path(ROOTS_DASHBOARD, '/blank'),
  misc: path(ROOTS_DASHBOARD, '/misc'),
  charts: path(ROOTS_DASHBOARD, '/charts'),
  componentsUi: path(ROOTS_DASHBOARD, '/components-ui'),
  componentsExtra: path(ROOTS_DASHBOARD, '/components-extra'),
  page: path(ROOTS_DASHBOARD, '/page'),
  pages: path(ROOTS_DASHBOARD, '/pages'),
  chat: path(ROOTS_DASHBOARD, '/chat'),
  mail: path(ROOTS_DASHBOARD, '/mail'),
  contact: path(ROOTS_DASHBOARD, '/contact'),
  faqs: path(ROOTS_DASHBOARD, '/faqs'),
  about: path(ROOTS_DASHBOARD, '/about'),
  landing: path(ROOTS_DASHBOARD, '/landing'),
  terms: path(ROOTS_DASHBOARD, '/terms'),
  privacy: path(ROOTS_DASHBOARD, '/privacy'),
  comingSoon: path(ROOTS_DASHBOARD, '/coming-soon'),
  maintenance: path(ROOTS_DASHBOARD, '/maintenance'),
  payment: path(ROOTS_DASHBOARD, '/payment'),
  page500: path(ROOTS_DASHBOARD, '/500'),
  page403: path(ROOTS_DASHBOARD, '/403'),
  page404: path(ROOTS_DASHBOARD, '/404'),
  page500Demo: path(ROOTS_DASHBOARD, '/500-demo'),
  page403Demo: path(ROOTS_DASHBOARD, '/403-demo'),
  page404Demo: path(ROOTS_DASHBOARD, '/404-demo'),
  docsComponents: path(ROOTS_DASHBOARD, '/docs/components'),
  docsHooks: path(ROOTS_DASHBOARD, '/docs/hooks'),
  docsIntroduction: path(ROOTS_DASHBOARD, '/docs/introduction'),
  docsMinimal: path(ROOTS_DASHBOARD, '/docs/minimal'),
  docsNavigation: path(ROOTS_DASHBOARD, '/docs/navigation'),
  docsOther: path(ROOTS_DASHBOARD, '/docs/other'),
  docsRouting: path(ROOTS_DASHBOARD, '/docs/routing'),
  docsStarting: path(ROOTS_DASHBOARD, '/docs/starting'),
  docsThemeColor: path(ROOTS_DASHBOARD, '/docs/theme-color'),
  docsThemeLayout: path(ROOTS_DASHBOARD, '/docs/theme-layout'),
  docsThemeTypography: path(ROOTS_DASHBOARD, '/docs/theme-typography'),
  docsTheming: path(ROOTS_DASHBOARD, '/docs/theming'),
  docsVersion: path(ROOTS_DASHBOARD, '/docs/version'),
  demo: path(ROOTS_DASHBOARD, '/demo'),
  order: path(ROOTS_DASHBOARD, '/order'),
  post: path(ROOTS_DASHBOARD, '/post'),
  productDemo: path(ROOTS_DASHBOARD, '/product-demo'),
  travel: path(ROOTS_DASHBOARD, '/travel'),
  tour: path(ROOTS_DASHBOARD, '/tour'),
  marketing: path(ROOTS_DASHBOARD, '/marketing'),
  career: path(ROOTS_DASHBOARD, '/career'),
  course: path(ROOTS_DASHBOARD, '/course'),
  job: path(ROOTS_DASHBOARD, '/job'),
  tourDemo: path(ROOTS_DASHBOARD, '/tour-demo'),
  travelDemo: path(ROOTS_DASHBOARD, '/travel-demo'),
  marketingDemo: path(ROOTS_DASHBOARD, '/marketing-demo'),
  careerDemo: path(ROOTS_DASHBOARD, '/career-demo'),
  courseDemo: path(ROOTS_DASHBOARD, '/course-demo'),
  jobDemo: path(ROOTS_DASHBOARD, '/job-demo'),
  ecommerceDemo: path(ROOTS_DASHBOARD, '/ecommerce-demo'),
  analyticsDemo: path(ROOTS_DASHBOARD, '/analytics-demo'),
  bankingDemo: path(ROOTS_DASHBOARD, '/banking-demo'),
  bookingDemo: path(ROOTS_DASHBOARD, '/booking-demo'),
  academyDemo: path(ROOTS_DASHBOARD, '/academy-demo'),
  mailDemo: path(ROOTS_DASHBOARD, '/mail-demo'),
  chatDemo: path(ROOTS_DASHBOARD, '/chat-demo'),
  calendarDemo: path(ROOTS_DASHBOARD, '/calendar-demo'),
  kanbanDemo: path(ROOTS_DASHBOARD, '/kanban-demo'),
  fileDemo: path(ROOTS_DASHBOARD, '/file-demo'),
  permissionDemo: path(ROOTS_DASHBOARD, '/permission-demo'),
  invoiceDemo: path(ROOTS_DASHBOARD, '/invoice-demo'),
  blogDemo: path(ROOTS_DASHBOARD, '/blog-demo'),
  postDemo: path(ROOTS_DASHBOARD, '/post-demo'),
  orderDemo: path(ROOTS_DASHBOARD, '/order-demo'),
  productDemoDemo: path(ROOTS_DASHBOARD, '/product-demo-demo'),
  general: path(ROOTS_DASHBOARD, '/general'),
  account: path(ROOTS_DASHBOARD, '/account'),
  blankDemo: path(ROOTS_DASHBOARD, '/blank-demo'),
  kanban: path(ROOTS_DASHBOARD, '/kanban'),
  file: path(ROOTS_DASHBOARD, '/file'),
  blog: path(ROOTS_DASHBOARD, '/blog'),
  postNew: path(ROOTS_DASHBOARD, '/post/new'),
  postEdit: (title) => path(ROOTS_DASHBOARD, `/post/${title}/edit`),
  postDemoEdit: path(ROOTS_DASHBOARD, '/post/apply-these-7-secret-techniques-to-improve-event/edit'),
};
