version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: eduqr_postgres
    environment:
      POSTGRES_DB: eduqr_db
      POSTGRES_USER: eduqr_user
      POSTGRES_PASSWORD: eduqr_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - eduqr_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  eduqr_network:
    driver: bridge 